### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by aknorw** [benrr101/node-taglib-sharp#18]
Hi,
First of all, thanks for that library that looks really promising.
Is there any reason why the node version is pinned to `12.16.1`?
Thanks!
Antoine

**Comment by benrr101** [comment]
Hi Antoine, thanks for reaching out and apologies for the delay in getting back. I work on this in my free time and must've missed the notification about this and your other issue. Tbh, I'm not really a node developer, so there's a few aspects I might get wrong. Node version is probably one of them. My assumption was that picking the oldest LTS would allow more users to use it, but must've missed the part about `engines` supporting `>=`. Assuming that's the right way to do this, I'll get it out as a hotfix quickly.

**Comment by benrr101** [comment]
Good news, this has been fixed in the latest release v3.3.0! You can now use any version `>=12.16.1`
