### ISSUE TITLE
Support lossless audio formats

### ISSUE THREAD

**Issue by aknorw** [benrr101/node-taglib-sharp#19]
It would be nice to support lossless audio formats (biggest ones being `aiff`, `flac` and `wav`).
Happy to help on this one, I'd just need directions to get started.

**Comment by benrr101** [comment]
Good news on that front - AIFF was just released a week ago!
Right now I'm going in alphabetical order down the list. ASF (Windows Media) is next, but I can prioritize FLAC after that.

I'd definitely appreciate any help to speed up this project! If you'd like to join in, WavPack would be decent to start with. It's only 2 classes, and they seem to be pretty straightforward. I'd start by forking this repo and branching off develop. The way I've been developing it so far, I have the mono/taglib-sharp code on one side of the screen, and node-taglib-sharp on the other, and just translate the C# code into typescript, class by class. Aside from the ID3vx folders, each format follows a pretty standard pattern you should be able to follow to implement WavPack. I'd greatly appreciate unit tests for the StreamHeader class and an integration test (which can be translated from the taglib-sharp project) for WavPack as a whole. Feel free to let me know if there's any other questions you might have.

**Comment by benrr101** [comment]
More good news - WAV file support was just added!

**Comment by benrr101** [comment]
Even more good news - FLAC file support was just added!
