### ISSUE TITLE
PopularimeterFrame

### ISSUE THREAD

**Issue by digimezzo** [benrr101/node-taglib-sharp#61]
I've been using TagLib# for years and in an audio player written in .NET, I was able to read and write to the PopularimeterFrame of MP3 files using Taglib#. My audio player has now been migrated to Electron, so I'm trying to read from and write to the PopularimeterFrame using your library. I've searched through the source code, but unfortunately it's not clear for me if this is possible.
Is this possible? If yes, how could I do this?
Thank you.

**Comment by benrr101** [comment]
Yep, the library does indeed support popularimeter frames! The docs for the frame is [here](https://github.com/benrr101/node-taglib-sharp/blob/release/v5.0.0/docs/classes/Id3v2PopularimeterFrame.md) but that probably doesn't tell you too much about how to use it. Same as TagLib#, the `PopularimeterFrame` isn't exposed via the standardized `Tag` interface, so you'll have to manipulate the frames directly. When you get to manipulating the frames directly, it can be a bit confusing. Here's an example:

```typescript
import {
    File,
    Id3v2Tag,
    Id3v2FrameClassType,
    Id3v2FrameIdentifiers,
    Id3v2PopularimeterFrame,
    TagTypes
} from "node-taglib-sharp";

const myFile = File.createFromPath("myFile.mp3");
const id3v2Tag = <Id3v2Tag>myFile.getTag(TagTypes.Id3v2, true);

// Read a popularimeter frame
const popularimeterFrames = id3v2Tag.getFramesByClassType<Id3v2PopularimeterFrame>(Id3v2FrameClassType.PopularimeterFrame);
console.log(popularimeterFrames[0].playCount);
console.log(popularimeterFrames[0].rating);

// Write a popularimeter frame directly
popularimeterFrames[0].user = "abc@123.com"; // ID3v2 Spec says it should be an email
popularimeterFrames[0].playCount = 10n; // It's a BigInt
popularimeterFrames[0].rating = 100; // It's a byte between 0 and 255
myFile.save();

// Write a new frame instead
const newPopularmieterFrame = Id3v2PopularimeterFrame.fromUser("abc@123");
newPopularmieterFrame.playCount = 10n;
newPopularmieterFrame.rating = 100;

id3v2Tag.removeFrames(Id3v2FrameIdentifiers.POPM);
id3v2Tag.addFrame(newPopularmieterFrame);
myFile.save();
```

Let me know if you have any questions or need clarification!

**Comment by digimezzo** [comment]
Thanks a lot for taking the time to help out! That's an amazing example. I should be able to get it working with this info.
