### ISSUE TITLE
Why Tag class has no accessor for 'artist' ?

### ISSUE THREAD

**Issue by stuartambient** [benrr101/node-taglib-sharp#93]
It seems more common to have an artist value, than albumArtists.  I am wrong because I do get returns with 'performers'.
Edit: Just tested, setting performers shows in the generic Artist field

> This field is most commonly called "Artists" in audio media or "Actors" in video media, and should be used to represent each artist/actor appearing in the media.

**Comment by benrr101** [comment]
Hi @stuartambient yep, you figured it out. This follows the same pattern as TagLib# and the original C++ TagLib of calling the artist field Performers. Don't ask my why the decided to call it that, but there aren't any plans to change it.
